### ISSUE TITLE
change relevant parts of the map to match inverted day/night colors

### ISSUE THREAD

**Issue by thinkberg** [ubirch/ubirch-app#3]
- show map in dark grey (original) during the day to be able to see the sensor colors clearly
- show map brighter during the night to better distinguish sensor colors (rather black probably)

**Comment by dutscher** [comment]
that means #333333 is the day color and #000000 the night color in the background?

**Comment by thinkberg** [comment]
the default night color should be what the default is right now.
for the I would invert it I guess. something to play with

**Comment by dutscher** [comment]
the detection is added. but we need to define the colors. 
now on day-time the colors are bg: #333333, none eu: #3d3d3d, eu: #515151 and hover: steelblue.

**Comment by thinkberg** [comment]
I found it works best the way it is.
