### ISSUE TITLE
add splashscreen

### ISSUE THREAD

**Issue by thinkberg** [ubirch/ubirch-app#4]

**Comment by dutscher** [comment]
all screens are created, but splashscreen plugin not included and tested

**Comment by dutscher** [comment]
android got 9.png to fit every device size. icons already show on device.

**Comment by dutscher** [comment]
we have to check out ios devices!

**Comment by thinkberg** [comment]
Is it possible to make the splash screen have the three lamp picture as on http://ubirch.com/about.html and the in cooperation with republica 2015?

**Comment by dutscher** [comment]
so its implement for ios and android :)
