### ISSUE TITLE
add eu country flags

### ISSUE THREAD

**Issue by thinkberg** [ubirch/ubirch-app#6]

**Comment by dutscher** [comment]
look at here https://www.flag-sprites.com/de_DE/ i prefer the "GoSquared large 32x32".
with this we have one image for all countries and a css for using them easily!

**Comment by thinkberg** [comment]
sounds good

**Comment by dutscher** [comment]
you missed cyprus!

**Comment by dutscher** [comment]
hu is missing says the console
