### ISSUE TITLE
imprint & credits

### ISSUE THREAD

**Issue by dutscher** [ubirch/ubirch-app#7]
we need a position for this

**Comment by thinkberg** [comment]
What about a Logo-Button top left of the map? It's more or less empty anyway?

**Comment by thinkberg** [comment]
This is the current list of contributors:

Basic Imprint: 
  ubirch GmbH (Stephan Noller)
  http://ubirch.com/imprint.html

Concept & Programming
  Matthias L. Jugel (http://twitter.com/thinkberg)
  Willy Woitas (???)

Design & Maps
  fuenfwerken Design AG (http://www.fuenfwerken.com)

Deployment
  indarium GmbH (http://indarium.de)

**Comment by dutscher** [comment]
its done when you like it :)

**Comment by thinkberg** [comment]
Hmm, nice, but I think it's a bit over the top. Use a circle that contains the leaf as a button and just open a blank page containing the credits with a back button that closes the overlay would be my wish.

**Comment by dutscher** [comment]
its done with an overlay. the leaf got a circle and shared his location with the close button.

**Comment by thinkberg** [comment]
somehow in a normal browser, if I opened the overlay once, and close it it is hidden, but a click still goes to the overlay and I can't select the map anymore.

**Comment by thinkberg** [comment]
running on ios-sim if I zoomed once and then click on the map in the upper half of the map the click goes to the credits overlay even though it is not visible. we need to make sure the credits panel is completely hidden or z-index below the map if not visible.

**Comment by dutscher** [comment]
its fixxed
